TT-10669 upgraded go version
TykTechnologies/tyk-identity-broker pull request #363
Opened 2024-01-11 14:44 UTC by sredxny

## Description
Upgraded go version to go 1.21

## Related Issue
TT-10669

## Motivation and Context
In order to keep up to date and in sync with other tyk components, upgraded the go version

## How This Has Been Tested
Compile app

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2024-01-11 15:57 UTC, tbuchaillot requested changes

2024-01-11 15:57 UTC, tbuchaillot commented on repo-policy/main.tf
> +	required_tests = ["1.21-bullseye"]}
I don't think this is necessary @sredxny since we are not updating go version in 1.4

2024-01-11 16:39 UTC, tbuchaillot approved these changes
LGTM

2024-01-12 09:52 UTC, ermirizio approved these changes
lgtm

2024-01-12 10:03 UTC, merged